/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.41
 * Generated at: 2017-05-28 06:39:07 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class booking_005fpage_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!doctype html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("\t<title>Booking</title>\r\n");
      out.write("\t<link rel=\"icon\"type=\"image\" href=\"Logo.jpg\"/>   <!--fav icon tag-->\r\n");
      out.write("</head>\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("\r\n");
      out.write(".cancelbtn, .bookbtn\r\n");
      out.write("{\r\n");
      out.write("  padding: 14px 20px;\r\n");
      out.write("  background-color: lightblue;\r\n");
      out.write("  \r\n");
      out.write("}\r\n");
      out.write("button .cancelbtn: hover\r\n");
      out.write("{\r\n");
      out.write("\tbox-shadow: 10px 10px 5px #;\r\n");
      out.write("}\r\n");
      out.write("button \r\n");
      out.write("{\r\n");
      out.write("    \r\n");
      out.write("    color: black;\r\n");
      out.write("    padding: 14px 20px;\r\n");
      out.write("    margin: 8px 0;\r\n");
      out.write("    border: none;\r\n");
      out.write("    cursor: pointer;\r\n");
      out.write("    width:200px;\r\n");
      out.write("    transition-duration: 0.4s;\r\n");
      out.write("}\r\n");
      out.write("input[type=text], input[type=password] \r\n");
      out.write("{\r\n");
      out.write("    width: 400px;\r\n");
      out.write("    padding: 12px 20px;\r\n");
      out.write("    margin: 8px 0;\r\n");
      out.write("    display: inline-block;\r\n");
      out.write("    border: 1px solid #ccc;\r\n");
      out.write("    box-sizing: border-box;\r\n");
      out.write("}\r\n");
      out.write("#regularbooking p\r\n");
      out.write("{\r\n");
      out.write("font-family: calibri;\r\n");
      out.write("font-size: 20px;\r\n");
      out.write("color: #B8860B;\r\n");
      out.write("}\r\n");
      out.write("body {\r\n");
      out.write("    background-image: url(\"68516858-notepad-wallpapers.jpeg\");\r\n");
      out.write("    background-size: 1366px auto;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div id=\"regularbooking\">\r\n");
      out.write("<center>\r\n");
      out.write("<p>Booking a truck has never been easier!</p>\r\n");
      out.write("<p>Submit the form and it's done</p>\r\n");
      out.write("<form id=\"frm_Newjoin\" method=\"post\" action=\"booking_conn.jsp\">\r\n");
      out.write("\t<input type=\"text\" name=\"user_name\" id=\"user_name\" placeholder=\"Name\"/><br><br>\r\n");
      out.write("\t<input type=\"text\" name=\"my_location\" id=\"txt_Pick-up\" placeholder=\"Pick-up location\"/><br><br>\r\n");
      out.write("\t<input type=\"text\" name=\"dest\" id=\"txt_Destination\" placeholder=\"Destination\"/><br><br>\r\n");
      out.write("\t<input type=\"text\" name=\"contact_no\" id=\"txt_Phone\" placeholder=\"Phone\"/><br><br>\r\n");
      out.write("\t<input type=\"text\" name=\"wor_force\" id=\"txt_Labour\" placeholder=\"Number of Labour\"/><br><br>\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t<button type=\"submit\" class=\"bookbtn\">BOOK</button>\r\n");
      out.write("\t<button type=\"submit\" class=\"cancelbtn\"><a href=\"profile.jsp\">BACK</a></button>\r\n");
      out.write("</form>\r\n");
      out.write("<h3 style=\"color:maroon; font-family:calibri;\">Having trouble booking?<br>\r\n");
      out.write("    call us @+91-98989898989</h3>\t\r\n");
      out.write("</center>\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
