/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.41
 * Generated at: 2017-05-27 17:56:16 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class profile_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!doctype html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("\t<title>LOG</title>\r\n");
      out.write("\t<link rel=\"icon\"type=\"image\" href=\"Logo.jpg\"/>   <!--fav icon tag-->\r\n");
      out.write("    \r\n");
      out.write("\t<style>\r\n");
      out.write("   \r\n");
      out.write("\r\n");
      out.write("   #header\r\n");
      out.write("  {\r\n");
      out.write("       position:relative;\r\n");
      out.write("       \r\n");
      out.write("       height:70px;\r\n");
      out.write("       width:1550px;\r\n");
      out.write("       margin-left: -8px;\r\n");
      out.write("       \r\n");
      out.write("  }\r\n");
      out.write("  #header_img\r\n");
      out.write("  {\r\n");
      out.write("       float:left;\r\n");
      out.write("       width: 100px;\r\n");
      out.write("       height: 80px;\r\n");
      out.write("       margin-left: 53px;\r\n");
      out.write("       \r\n");
      out.write("\r\n");
      out.write("  }\r\n");
      out.write("  #header_img p\r\n");
      out.write("  {\r\n");
      out.write("    font-size: 50px;\r\n");
      out.write("    color:white;\r\n");
      out.write("    font-family: BankGothic Lt BT;\r\n");
      out.write("    margin-bottom: -20px;\r\n");
      out.write("    text-align: center;\r\n");
      out.write("    margin-top: 10px;\r\n");
      out.write("    margin-left: -5px;\r\n");
      out.write("  }\r\n");
      out.write("  #header_img h6\r\n");
      out.write("  {\r\n");
      out.write("   color: white;\r\n");
      out.write("    font-family: BankGothic Lt BT; \r\n");
      out.write("    \r\n");
      out.write("  }\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("  \r\n");
      out.write("  #mid_header h2\r\n");
      out.write("  {\r\n");
      out.write("     float:left;\r\n");
      out.write("     text-align:center;\r\n");
      out.write("     height:40px;\r\n");
      out.write("     line-height:50px;\r\n");
      out.write("     cursor:pointer;\r\n");
      out.write("     font-family: Calibri;\r\n");
      out.write("     margin-left: 250px;\r\n");
      out.write("    float:left;\r\n");
      out.write("     list-style:none; \r\n");
      out.write("     height:60px;\r\n");
      out.write("   margin-bottom: 50px;\r\n");
      out.write("}\r\n");
      out.write("  #mid_header h2\r\n");
      out.write("  {\r\n");
      out.write("     color:white;\r\n");
      out.write("     \r\n");
      out.write("   }\r\n");
      out.write("  \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(" #right_header ul\r\n");
      out.write("   {\r\n");
      out.write("   \tmargin-left: 500px;\r\n");
      out.write("   \tfloat:left;\r\n");
      out.write("     list-style:none; \r\n");
      out.write("    height:60px;\r\n");
      out.write("   }\r\n");
      out.write("     #right_header ul li\r\n");
      out.write("  {\r\n");
      out.write("     float:left;\r\n");
      out.write("     font-size:16px;\r\n");
      out.write("     width:120px;\r\n");
      out.write("     text-align:center;\r\n");
      out.write("     height:40px;\r\n");
      out.write("     line-height:50px;\r\n");
      out.write("     \r\n");
      out.write("     cursor:pointer;\r\n");
      out.write("     font-family: Calibri;\r\n");
      out.write("}\r\n");
      out.write("    #right_header ul li a\r\n");
      out.write("  {\r\n");
      out.write("     color:white;\r\n");
      out.write("     text-decoration:none;\r\n");
      out.write("   }\r\n");
      out.write("   #right_header ul li:hover\r\n");
      out.write("\r\n");
      out.write("   {\r\n");
      out.write("    color: lightblue;\r\n");
      out.write("   font-size:20px;\r\n");
      out.write("   font-style:bold;\r\n");
      out.write("    opacity: 0.5;\r\n");
      out.write(" filter: Alpha(opacity=50);\r\n");
      out.write("\r\n");
      out.write("   }\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("#header\r\n");
      out.write("{\r\n");
      out.write("\tpadding-top: 5px;\r\n");
      out.write("\tbackground-color:  #2F4F4F;\r\n");
      out.write("\theight: 100px;\r\n");
      out.write("\t  position:relative;\r\n");
      out.write("}\r\n");
      out.write("#right_header ul li a button \r\n");
      out.write("{\r\n");
      out.write("    background-color:   #20B2AA;\r\n");
      out.write("    color: white;\r\n");
      out.write("    padding: 14px 20px;\r\n");
      out.write("    margin: 8px 0;\r\n");
      out.write("    border: none;\r\n");
      out.write("    cursor: pointer;\r\n");
      out.write("    width: 100%;\r\n");
      out.write("    transition-duration: 0.4s;\r\n");
      out.write("}\r\n");
      out.write("#right_header ul li a button:hover\r\n");
      out.write("{\r\n");
      out.write("   opacity: 0.5;\r\n");
      out.write(" filter: Alpha(opacity=50);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("#navigation\r\n");
      out.write("{\r\n");
      out.write("height:40px;\r\n");
      out.write("background:black;\r\n");
      out.write("margin-left: -10px;\r\n");
      out.write("width: 1366px;\r\n");
      out.write("}\r\n");
      out.write(" #navigation ul\r\n");
      out.write("  {\r\n");
      out.write("     margin:0px;\r\n");
      out.write("     padding:0px;\r\n");
      out.write("     list-style:none; \r\n");
      out.write("  }\r\n");
      out.write("  \r\n");
      out.write("  #navigation ul li\r\n");
      out.write("  {\r\n");
      out.write("     float:left;\r\n");
      out.write("     font-size:16px;\r\n");
      out.write("     width:223px;\r\n");
      out.write("     text-align:center;\r\n");
      out.write("     height:40px;\r\n");
      out.write("     line-height:40px;\r\n");
      out.write("     display:block;\r\n");
      out.write("     cursor:pointer;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("  #navigation ul li a\r\n");
      out.write("  {\r\n");
      out.write("     color:white;\r\n");
      out.write("     text-decoration:none;\r\n");
      out.write("   }\r\n");
      out.write("  #navigation ul li:hover\r\n");
      out.write("\r\n");
      out.write("   {\r\n");
      out.write("    color: black;\r\n");
      out.write("   background:#20B2AA;\r\n");
      out.write("   font-size:16px;\r\n");
      out.write("   font-style:italic;\r\n");
      out.write("  \r\n");
      out.write("    transform: rotateY(360deg);\r\n");
      out.write("    transition-duration: 1s;\r\n");
      out.write(" \r\n");
      out.write("  box-shadow: 5px 5px 6px grey;\r\n");
      out.write("\r\n");
      out.write("   }\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\t<body>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<div id=\"container\">   <!--main division start-->\r\n");
      out.write("\t\t<div id=\"header\">  <!--Header division start-->\r\n");
      out.write("\t\t<div id=\"header_img\"><p>LOG</p><h6>LOAD OUR GOODS</h6>\r\n");
      out.write("          \r\n");
      out.write("\r\n");
      out.write("  \r\n");
      out.write("\t\t</div>\t\r\n");
      out.write("\t\t\t\t \r\n");
      out.write("\t\t<div id=\"mid_header\">\t\t\r\n");
      out.write("<h2>USER PROFILE</h2>\r\n");
      out.write("</div> \r\n");
      out.write(" <div id=\"right_header\">\r\n");
      out.write("      <ul>\r\n");
      out.write("      <li><a href=\"signout.jsp\"><button style=\"width:auto;\">SIGN OUT</button></a></li>\r\n");
      out.write("      <li><a href=\"change_pass.jsp\">Change<br>Password</a></li> </div>     \r\n");
      out.write("      </ul>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("  <div id=\"navigation\">    \r\n");
      out.write("<ul>\r\n");
      out.write(" <li><a href=\"booking_page.jsp\">BOOKING</a></li>\r\n");
      out.write("      <li><a href=\"welcome.jsp\">PROFILE</a></li>\r\n");
      out.write("      <li><a href=\"history.jsp\">HISTORY</a></li>\r\n");
      out.write("      \r\n");
      out.write("</ul>\r\n");
      out.write("</div>   \r\n");
      out.write("</div><!--Header division ends-->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</div><!--main division ends-->\r\n");
      out.write("<form action = \"feedbackform.jsp\" method = post>\r\n");
      out.write("<button type=\"submit\">feedback</button>\r\n");
      out.write("</form>\r\n");
      out.write("\t\t\r\n");
      out.write("\t</body>\r\n");
      out.write("</head>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
